### ISSUE TITLE
Auto Credit past contributions

### ISSUE THREAD

**Issue by yosefromano** [MegaphoneJon/automaticsoftcredit#2]
Is there a way to update all previous contributions to auto soft credit relationships?

**Comment by MegaphoneJon** [comment]
Not with this extension, no.  I suppose if you wanted to, and you could ensure no one else was using the database, you could use the [command-line track](https://civicrm.stackexchange.com/a/33165/12) I posted to you about yesterday on Stack Exchange, except to do a `drush cvapi Contribution.create id=x`.  This will trigger an "edit" on each contribution.  If you change the `create` in [this line](https://github.com/MegaphoneJon/automaticsoftcredit/blob/master/automaticsoftcredit.php#L8) to `edit` before running the API call, this will do the job you're requesting.  Be sure to set it back afterward!

I did recently have to update previous contributions for someone who I installed this extension for.  My notes say I used this SQL (use at your own risk, test on a test site first, etc.):
```sql
INSERT INTO civicrm_contribution_soft (contribution_id, contact_id, amount, currency, soft_credit_type_id)
SELECT cont.id, cr.contact_id_b, cont.total_amount, cont.currency, 4 from civicrm_contact cc JOIN civicrm_relationship cr ON cr.contact_id_a = cc.id AND cr.relationship_type_id = 2 JOIN civicrm_contribution cont ON cc.id = cont.contact_id;

INSERT INTO civicrm_contribution_soft (contribution_id, contact_id, amount, currency, soft_credit_type_id)
SELECT cont.id, cr.contact_id_a, cont.total_amount, cont.currency, 4 from civicrm_contact cc JOIN civicrm_relationship cr ON cr.contact_id_b = cc.id AND cr.relationship_type_id = 2 JOIN civicrm_contribution cont ON cc.id = cont.contact_id;
```

Looking at this now, here are my notes:
* There are two separate SQL commands because they chose the "Soft Credit in both directions" option.  If you want to soft credit from A to B, you just use the first statement; from B to A, use the second statement.
* The `4` in each statement is the soft credit type ID.
* The `2` in each statement is the relationship type ID they wanted to soft credit on.
